"""Auditable group manifests and group-safe diagnostic splits for NKSID.

The public NKSID release does not contain acquisition/mission identifiers.
Consequently, manifests generated by this module from image similarity are
explicitly *stress-test* metadata and never acquisition evidence.  A group
generalisation claim is enabled only for a complete user-provided manifest.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from random import Random
from typing import Any, Mapping, Sequence

import numpy as np
from PIL import Image

from .protocol import ProtocolError, ProtocolSplit, class_counts


GROUP_MANIFEST_SCHEMA = "nksid_group_manifest_v1"
GROUP_POLICIES = {"none", "provided", "inferred_stress"}


def _relative_sample_path(path: str | Path, root: Path) -> str:
    resolved = Path(path).resolve()
    try:
        return resolved.relative_to(root.resolve()).as_posix()
    except ValueError:
        return resolved.as_posix()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _phash64(path: Path) -> int:
    """Return a deterministic 64-bit perceptual hash without extra packages."""
    with Image.open(path) as source:
        image = source.convert("L").resize((32, 32), Image.Resampling.LANCZOS)
        values = np.asarray(image, dtype=np.float64)

    n = 32
    positions = np.arange(n, dtype=np.float64)
    frequencies = np.arange(8, dtype=np.float64)[:, None]
    basis = np.cos((np.pi / n) * (positions + 0.5) * frequencies)
    basis[0] *= np.sqrt(1.0 / n)
    basis[1:] *= np.sqrt(2.0 / n)
    low_frequency = basis @ values @ basis.T
    coefficients = low_frequency[:8, :8].reshape(-1)
    threshold = float(np.median(coefficients[1:]))
    bits = coefficients > threshold
    value = 0
    for index, enabled in enumerate(bits.tolist()):
        if enabled:
            value |= 1 << index
    return value


class _DisjointSet:
    def __init__(self, size: int) -> None:
        self.parent = list(range(size))

    def find(self, item: int) -> int:
        while self.parent[item] != item:
            self.parent[item] = self.parent[self.parent[item]]
            item = self.parent[item]
        return item

    def union(self, left: int, right: int) -> None:
        left_root = self.find(left)
        right_root = self.find(right)
        if left_root != right_root:
            self.parent[right_root] = left_root


def build_inferred_group_manifest(
    samples: Sequence[tuple[str, int]],
    data_dir: str | Path,
    *,
    hamming_threshold: int = 4,
) -> dict[str, Any]:
    """Build a class-local pHash connected-component stress manifest."""
    if not 0 <= int(hamming_threshold) <= 64:
        raise ValueError("hamming_threshold must be in [0, 64]")
    root = Path(data_dir).expanduser().resolve()
    nested = root / "NKSID"
    if nested.is_dir():
        root = nested

    rows: list[dict[str, Any]] = []
    hashes: list[int] = []
    for index, (raw_path, label) in enumerate(samples):
        path = Path(raw_path).resolve()
        if not path.is_file():
            raise FileNotFoundError(f"group manifest sample is missing: {path}")
        with Image.open(path) as image:
            width, height = image.size
        phash = _phash64(path)
        hashes.append(phash)
        rows.append(
            {
                "sample_index": index,
                "sample_path": _relative_sample_path(path, root),
                "label": int(label),
                "group_id": None,
                "group_source": "inferred_phash_stress",
                "original_width": int(width),
                "original_height": int(height),
                "sha256": _sha256(path),
                "phash64": f"{phash:016x}",
            }
        )

    disjoint = _DisjointSet(len(rows))
    by_class: dict[int, list[int]] = {}
    for index, row in enumerate(rows):
        by_class.setdefault(int(row["label"]), []).append(index)
    threshold = int(hamming_threshold)
    for indices in by_class.values():
        for offset, left in enumerate(indices):
            for right in indices[offset + 1 :]:
                if (hashes[left] ^ hashes[right]).bit_count() <= threshold:
                    disjoint.union(left, right)

    component_ids: dict[tuple[int, int], str] = {}
    component_counts: dict[str, int] = {}
    for index, row in enumerate(rows):
        key = (int(row["label"]), disjoint.find(index))
        if key not in component_ids:
            component_ids[key] = f"inferred_c{key[0]:02d}_g{len(component_ids):04d}"
        group_id = component_ids[key]
        row["group_id"] = group_id
        component_counts[group_id] = component_counts.get(group_id, 0) + 1

    return {
        "schema_version": 1,
        "schema": GROUP_MANIFEST_SCHEMA,
        "group_policy": "inferred_stress",
        "group_generalization_claimable": False,
        "claim_boundary": (
            "Class-local pHash connected components are a near-duplicate leakage "
            "stress test; they are not acquisition, mission, source-frame, or target-instance groups."
        ),
        "data_root": str(root),
        "hamming_threshold": threshold,
        "sample_count": len(rows),
        "group_count": len(component_counts),
        "max_group_size": max(component_counts.values(), default=0),
        "samples": rows,
    }


def write_group_manifest(path: str | Path, payload: Mapping[str, Any]) -> Path:
    target = Path(path).expanduser().resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(dict(payload), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return target


@dataclass(frozen=True)
class ResolvedGroups:
    group_ids: tuple[str, ...]
    policy: str
    manifest_path: str
    manifest_sha256: str
    generalization_claimable: bool
    source_values: tuple[str, ...]


def load_group_manifest(
    manifest_path: str | Path,
    samples: Sequence[tuple[str, int]],
    data_dir: str | Path,
    *,
    policy: str,
) -> ResolvedGroups:
    normalized_policy = str(policy).strip().lower()
    if normalized_policy not in {"provided", "inferred_stress"}:
        raise ValueError("group manifest policy must be 'provided' or 'inferred_stress'")
    path = Path(manifest_path).expanduser().resolve()
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("schema") != GROUP_MANIFEST_SCHEMA:
        raise ProtocolError(f"unsupported group manifest schema: {payload.get('schema')!r}")
    rows = payload.get("samples")
    if not isinstance(rows, list) or len(rows) != len(samples):
        raise ProtocolError(
            f"group manifest must contain exactly {len(samples)} samples, got "
            f"{len(rows) if isinstance(rows, list) else 'invalid'}"
        )

    root = Path(data_dir).expanduser().resolve()
    nested = root / "NKSID"
    if nested.is_dir():
        root = nested
    expected: dict[str, tuple[int, int]] = {
        _relative_sample_path(raw_path, root): (index, int(label))
        for index, (raw_path, label) in enumerate(samples)
    }
    group_ids: list[str | None] = [None] * len(samples)
    sources: set[str] = set()
    seen_paths: set[str] = set()
    for row in rows:
        sample_path = str(row.get("sample_path", "")).replace("\\", "/")
        if sample_path not in expected or sample_path in seen_paths:
            raise ProtocolError(f"group manifest has unknown or duplicate sample: {sample_path!r}")
        index, expected_label = expected[sample_path]
        if int(row.get("label", -1)) != expected_label:
            raise ProtocolError(f"group manifest label mismatch for {sample_path}")
        group_id = str(row.get("group_id", "")).strip()
        source = str(row.get("group_source", "")).strip()
        if not group_id or not source:
            raise ProtocolError(f"group manifest lacks group_id/source for {sample_path}")
        group_ids[index] = group_id
        sources.add(source)
        seen_paths.add(sample_path)
    if any(value is None for value in group_ids):
        raise ProtocolError("group manifest does not cover every dataset sample")
    if normalized_policy == "provided" and sources != {"provided"}:
        raise ProtocolError(
            "group_policy='provided' requires every group_source to equal 'provided'"
        )
    if normalized_policy == "inferred_stress" and "provided" in sources:
        raise ProtocolError("inferred_stress manifest must not mix provided acquisition groups")

    return ResolvedGroups(
        group_ids=tuple(str(value) for value in group_ids),
        policy=normalized_policy,
        manifest_path=str(path),
        manifest_sha256=_sha256(path),
        generalization_claimable=normalized_policy == "provided",
        source_values=tuple(sorted(sources)),
    )


def _assign_groups_to_folds(
    samples: Sequence[tuple[str, int]],
    groups: Sequence[str],
    *,
    folds: int,
    seed: int,
) -> list[list[int]]:
    grouped: dict[str, list[int]] = {}
    for index, group_id in enumerate(groups):
        grouped.setdefault(str(group_id), []).append(index)
    by_class: dict[int, list[tuple[str, list[int]]]] = {}
    for group_id, indices in grouped.items():
        labels = {int(samples[index][1]) for index in indices}
        if len(labels) != 1:
            raise ProtocolError(f"group {group_id!r} spans multiple class labels")
        by_class.setdefault(labels.pop(), []).append((group_id, indices))

    assignments: list[list[int]] = [[] for _ in range(folds)]
    counts: list[dict[int, int]] = [dict() for _ in range(folds)]
    rng = Random(seed)
    for label in sorted(by_class):
        entries = list(by_class[label])
        rng.shuffle(entries)
        entries.sort(key=lambda item: len(item[1]), reverse=True)
        for _, indices in entries:
            minimum = min(counts[fold].get(label, 0) for fold in range(folds))
            candidates = [
                fold for fold in range(folds) if counts[fold].get(label, 0) == minimum
            ]
            chosen = min(candidates, key=lambda fold: (len(assignments[fold]), fold))
            assignments[chosen].extend(indices)
            counts[chosen][label] = counts[chosen].get(label, 0) + len(indices)
    return [sorted(indices) for indices in assignments]


def _group_inner_split(
    samples: Sequence[tuple[str, int]],
    outer_train: Sequence[int],
    groups: Sequence[str],
    *,
    val_fraction: float,
    seed: int,
) -> tuple[tuple[int, ...], tuple[int, ...]]:
    if not 0.0 < val_fraction < 1.0:
        raise ValueError("val_fraction must be in (0, 1)")
    grouped: dict[str, list[int]] = {}
    for index in outer_train:
        grouped.setdefault(str(groups[index]), []).append(int(index))
    by_class: dict[int, list[tuple[str, list[int]]]] = {}
    for group_id, indices in grouped.items():
        labels = {int(samples[index][1]) for index in indices}
        if len(labels) != 1:
            raise ProtocolError(f"group {group_id!r} spans multiple class labels")
        by_class.setdefault(labels.pop(), []).append((group_id, indices))

    train: list[int] = []
    validation: list[int] = []
    rng = Random(seed)
    for label in sorted(by_class):
        entries = list(by_class[label])
        rng.shuffle(entries)
        target = max(1, round(sum(len(indices) for _, indices in entries) * val_fraction))
        selected = 0
        for position, (_, indices) in enumerate(entries):
            groups_left = len(entries) - position
            if selected < target and groups_left > 1:
                validation.extend(indices)
                selected += len(indices)
            else:
                train.extend(indices)
        if not any(int(samples[index][1]) == label for index in train):
            raise ProtocolError(f"group split left class {label} without training samples")
    return tuple(sorted(train)), tuple(sorted(validation))


def build_group_protocol_split(
    samples: Sequence[tuple[str, int]],
    resolved: ResolvedGroups,
    *,
    fold_index: int,
    seed: int,
    inner_val_fraction: float,
    num_classes: int,
) -> ProtocolSplit:
    """Build a five-fold group-disjoint diagnostic or provided-group split."""
    outer_folds = _assign_groups_to_folds(
        samples, resolved.group_ids, folds=5, seed=20260723
    )
    if not 0 <= int(fold_index) < len(outer_folds):
        raise ProtocolError("fold_index must be in [0, 5)")
    outer_val = tuple(outer_folds[int(fold_index)])
    outer_val_set = set(outer_val)
    outer_train = tuple(index for index in range(len(samples)) if index not in outer_val_set)
    inner_train, inner_val = _group_inner_split(
        samples,
        outer_train,
        resolved.group_ids,
        val_fraction=inner_val_fraction,
        seed=seed,
    )

    train_groups = {resolved.group_ids[index] for index in inner_train}
    inner_groups = {resolved.group_ids[index] for index in inner_val}
    outer_groups = {resolved.group_ids[index] for index in outer_val}
    if train_groups & inner_groups or train_groups & outer_groups or inner_groups & outer_groups:
        raise ProtocolError("group-safe split leaked a group across partitions")

    return ProtocolSplit(
        fold_index=int(fold_index),
        seed=int(seed),
        train_indices=inner_train,
        inner_val_indices=inner_val,
        outer_val_indices=outer_val,
        inner_val_fraction=float(inner_val_fraction),
        metadata={
            "protocol": "nksid_group_disjoint_outer5fold_v1",
            "group_policy": resolved.policy,
            "group_split_available": True,
            "group_generalization_claimable": resolved.generalization_claimable,
            "group_metadata_source": list(resolved.source_values),
            "group_manifest_path": resolved.manifest_path,
            "group_manifest_sha256": resolved.manifest_sha256,
            "group_claim_boundary": (
                "Acquisition-group generalization is claimable."
                if resolved.generalization_claimable
                else "Inferred image-similarity groups provide leakage stress testing only."
            ),
            "train_group_count": len(train_groups),
            "inner_val_group_count": len(inner_groups),
            "outer_val_group_count": len(outer_groups),
            "train_class_counts": class_counts(samples, inner_train, num_classes=num_classes),
            "inner_val_class_counts": class_counts(samples, inner_val, num_classes=num_classes),
            "outer_val_class_counts": class_counts(samples, outer_val, num_classes=num_classes),
        },
    )
