#!/usr/bin/env python3
"""Run full-network integer C-sim parity for frozen four-stage candidates.

This gate consumes the real-checkpoint, training-only activation-calibrated
Python INT8 reference generated by ``run_fourstage_int8_reference_gate.py`` and
builds one Vitis HLS C-simulation harness per deployment candidate.

The generated C++ is deliberately a C-sim parity harness, not the synthesizable
full-network datapath.  Passing this script means only:

* the same quantized weights, activation scales, rounding, saturation and
  residual semantics reproduce the Python INT8 reference logits exactly; and
* C-sim ran successfully for the preregistered representative checkpoints.

It does not claim RTL co-sim, complete-network HLS synthesis, place-and-route,
bitstream generation, COM5 board execution, or measured power.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import json
import math
from pathlib import Path
import subprocess
import sys
from textwrap import dedent
from typing import Any

import torch


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hwnas_fpga.deploy.fixed_point import (  # noqa: E402
    quantize_symmetric_int8,
    scale_to_multiplier,
)
from hwnas_fpga.deploy.inference import load_checkpoint_model  # noqa: E402
from hwnas_fpga.fourstage_int8_reference import (  # noqa: E402
    CALIBRATION_CONTRACT,
    _quantized_conv,
    _quantized_linear,
    validate_reference_supported_model,
)
from hwnas_fpga.fourstage_selection import canonical_sha256  # noqa: E402
from hwnas_fpga.models.builder import ConvBlock, MBConvBlock, SkipBlock  # noqa: E402
from hwnas_fpga.training.protocol_reporting import sha256_file  # noqa: E402


DEFAULT_INT8_SUMMARY = (
    ROOT
    / "artifacts"
    / "sonar_fourstage_operator_v2"
    / "fourstage_int8_reference_summary.json"
)
DEFAULT_OUTPUT_ROOT = (
    ROOT
    / "results"
    / "sonar_fourstage_operator_v2"
    / "full_network_deployment_closure"
)
DEFAULT_SUMMARY = (
    ROOT
    / "artifacts"
    / "sonar_fourstage_operator_v2"
    / "fourstage_csim_zero_mismatch_summary.json"
)
DEFAULT_VITIS_HLS = Path("F:/vivado/Vitis_HLS/2023.2/bin/vitis_hls.bat")
INPUT_SIZE = 1 * 224 * 224
OUTPUT_CLASSES = 8


@dataclass(frozen=True)
class TensorShape:
    channels: int
    height: int
    width: int

    @property
    def size(self) -> int:
        return int(self.channels * self.height * self.width)


@dataclass(frozen=True)
class ConvLayerSpec:
    identifier: str
    input_shape: TensorShape
    output_shape: TensorShape
    kernel_h: int
    kernel_w: int
    stride: int
    pad_h: int
    pad_w: int
    groups: int
    weights: list[int]
    bias: list[int]
    multiplier_numerator: int
    multiplier_denominator: int
    activation: str
    activation_upper: int


@dataclass(frozen=True)
class LinearLayerSpec:
    identifier: str
    in_features: int
    out_features: int
    weights: list[int]
    bias: list[int]
    multiplier_numerator: int
    multiplier_denominator: int


class CppNetworkEmitter:
    """Emit candidate-specific C++ that mirrors the Python INT8 reference."""

    def __init__(self, model: torch.nn.Module, calibration: dict[str, Any]):
        validate_reference_supported_model(model)
        self.model = model.eval()
        self.scales = {
            str(key): float(value) for key, value in calibration["scales"].items()
        }
        self.conv_layers: list[ConvLayerSpec] = []
        self.linear_layers: list[LinearLayerSpec] = []
        self.ops: list[str] = []
        self.current_shape = TensorShape(1, 224, 224)
        self.current_scale = float(self.scales["input"])

    @staticmethod
    def _identifier(name: str) -> str:
        cleaned = "".join(ch if ch.isalnum() else "_" for ch in name)
        while "__" in cleaned:
            cleaned = cleaned.replace("__", "_")
        return cleaned.strip("_")

    @staticmethod
    def _same_scale(left: float, right: float) -> bool:
        return math.isclose(float(left), float(right), rel_tol=0.0, abs_tol=1e-15)

    @staticmethod
    def _relu6_upper(output_scale: float) -> int:
        return min(127, max(0, int(round(6.0 / float(output_scale)))))

    def _scale_ratio(self, input_scale: float, weight_scale: float, output_scale: float) -> tuple[int, int]:
        return scale_to_multiplier(float(input_scale) * float(weight_scale) / float(output_scale))

    def _rescale_ratio(self, input_scale: float, output_scale: float) -> tuple[int, int] | None:
        if self._same_scale(input_scale, output_scale):
            return None
        return scale_to_multiplier(float(input_scale) / float(output_scale))

    def add_conv(
        self,
        *,
        name: str,
        conv: torch.nn.Conv2d,
        bn: torch.nn.BatchNorm2d,
        output_scale: float,
        activation: str | None,
    ) -> None:
        qconv = _quantized_conv(conv, bn, input_scale=float(self.current_scale))
        stride_h, stride_w = tuple(int(value) for value in conv.stride)
        pad_h, pad_w = tuple(int(value) for value in conv.padding)
        if stride_h != stride_w:
            raise ValueError(f"{name}: only equal H/W stride is supported")
        in_c, in_h, in_w = (
            int(conv.in_channels),
            int(self.current_shape.height),
            int(self.current_shape.width),
        )
        kernel_h, kernel_w = tuple(int(value) for value in conv.kernel_size)
        out_h = (in_h + 2 * pad_h - kernel_h) // stride_h + 1
        out_w = (in_w + 2 * pad_w - kernel_w) // stride_w + 1
        output_shape = TensorShape(int(conv.out_channels), out_h, out_w)
        numerator, denominator = self._scale_ratio(
            self.current_scale,
            qconv.weight_scale,
            float(output_scale),
        )
        identifier = self._identifier(name)
        layer = ConvLayerSpec(
            identifier=identifier,
            input_shape=TensorShape(in_c, in_h, in_w),
            output_shape=output_shape,
            kernel_h=kernel_h,
            kernel_w=kernel_w,
            stride=stride_h,
            pad_h=pad_h,
            pad_w=pad_w,
            groups=int(conv.groups),
            weights=[int(value) for value in qconv.weight.reshape(-1).tolist()],
            bias=[int(value) for value in qconv.bias.reshape(-1).tolist()],
            multiplier_numerator=int(numerator),
            multiplier_denominator=int(denominator),
            activation=activation or "none",
            activation_upper=(
                self._relu6_upper(output_scale) if activation == "relu6" else 127
            ),
        )
        self.conv_layers.append(layer)
        self.ops.append(f"  conv2d_layer(x, y, L_{identifier});")
        self.ops.append("  x.swap(y);")
        self.current_shape = output_shape
        self.current_scale = float(output_scale)

    def add_residual(self, *, input_scale: float, output_scale: float) -> None:
        ratio = self._rescale_ratio(input_scale, output_scale)
        self.ops.append("    std::vector<i8> identity;")
        if ratio is None:
            self.ops.append("    identity = residual;")
        else:
            numerator, denominator = ratio
            self.ops.append(
                f"    rescale_tensor(residual, identity, {int(numerator)}LL, {int(denominator)}LL);"
            )
        self.ops.append("    residual_add_tensor(x, identity, y);")
        self.ops.append("    x.swap(y);")
        self.current_scale = float(output_scale)

    def add_linear(self, *, name: str, linear: torch.nn.Linear, output_scale: float) -> None:
        qlinear = _quantized_linear(linear, input_scale=float(self.current_scale))
        numerator, denominator = self._scale_ratio(
            self.current_scale,
            qlinear.weight_scale,
            float(output_scale),
        )
        identifier = self._identifier(name)
        layer = LinearLayerSpec(
            identifier=identifier,
            in_features=int(linear.in_features),
            out_features=int(linear.out_features),
            weights=[int(value) for value in qlinear.weight.reshape(-1).tolist()],
            bias=(
                [0 for _ in range(int(linear.out_features))]
                if qlinear.bias is None
                else [int(value) for value in qlinear.bias.reshape(-1).tolist()]
            ),
            multiplier_numerator=int(numerator),
            multiplier_denominator=int(denominator),
        )
        self.linear_layers.append(layer)
        self.ops.append(f"  linear_layer(x, y, L_{identifier});")
        self.ops.append("  x.swap(y);")
        self.current_shape = TensorShape(int(linear.out_features), 1, 1)
        self.current_scale = float(output_scale)

    def add_gap(self, *, output_scale: float) -> None:
        shape = self.current_shape
        self.ops.append(
            f"  avg_pool_global(x, y, {shape.channels}, {shape.height}, {shape.width});"
        )
        self.ops.append("  x.swap(y);")
        ratio = self._rescale_ratio(self.current_scale, output_scale)
        if ratio is not None:
            numerator, denominator = ratio
            self.ops.append(
                f"  rescale_tensor(x, y, {int(numerator)}LL, {int(denominator)}LL);"
            )
            self.ops.append("  x.swap(y);")
        self.current_shape = TensorShape(shape.channels, 1, 1)
        self.current_scale = float(output_scale)

    def emit_model_ops(self) -> None:
        stem_block = self.model.stem.conv
        if not isinstance(stem_block, ConvBlock):
            raise ValueError("four-stage stem must contain ConvBlock stem.conv")
        self.add_conv(
            name="stem_conv",
            conv=stem_block.conv,
            bn=stem_block.bn,
            output_scale=float(self.scales["stem.conv"]),
            activation="relu",
        )

        for stage_index, stage in enumerate(self.model.stages):
            for block_index, block in enumerate(stage):
                name = f"stages.{stage_index}.{block_index}"
                if isinstance(block, ConvBlock):
                    self.add_conv(
                        name=name,
                        conv=block.conv,
                        bn=block.bn,
                        output_scale=float(self.scales[name]),
                        activation="relu",
                    )
                elif isinstance(block, MBConvBlock):
                    residual_scale = float(self.current_scale)
                    if block.use_residual:
                        self.ops.append("  {")
                        self.ops.append("    std::vector<i8> residual = x;")
                    if block.use_expand:
                        self.add_conv(
                            name=f"{name}.expand",
                            conv=block.expand_conv,
                            bn=block.expand_bn,
                            output_scale=float(self.scales[f"{name}.expand_relu"]),
                            activation="relu6",
                        )
                    self.add_conv(
                        name=f"{name}.dw",
                        conv=block.dw_conv,
                        bn=block.dw_bn,
                        output_scale=float(self.scales[f"{name}.dw_relu"]),
                        activation="relu6",
                    )
                    self.add_conv(
                        name=f"{name}.project",
                        conv=block.project_conv,
                        bn=block.project_bn,
                        output_scale=float(self.scales[name]),
                        activation=None,
                    )
                    if block.use_residual:
                        self.add_residual(
                            input_scale=residual_scale,
                            output_scale=float(self.scales[name]),
                        )
                        self.ops.append("  }")
                elif isinstance(block, SkipBlock):
                    if not block.use_conv:
                        continue
                    self.add_conv(
                        name=name,
                        conv=block.conv,
                        bn=block.bn,
                        output_scale=float(self.scales[name]),
                        activation=None,
                    )
                else:  # pragma: no cover - validate_reference_supported_model catches this.
                    raise ValueError(f"unsupported block: {block.__class__.__name__}")

        self.add_gap(output_scale=float(self.scales["head.gap"]))
        self.add_linear(
            name="head.fc",
            linear=self.model.head.fc,
            output_scale=float(self.scales["head.fc"]),
        )

    @staticmethod
    def _array_initializer(values: list[int], *, per_line: int = 24) -> str:
        chunks = []
        for offset in range(0, len(values), per_line):
            chunk = ", ".join(str(int(value)) for value in values[offset : offset + per_line])
            chunks.append(f"  {chunk}")
        return ",\n".join(chunks)

    def _emit_layer_arrays(self) -> str:
        pieces: list[str] = []
        for layer in self.conv_layers:
            pieces.append(
                f"static const i8 W_{layer.identifier}[{len(layer.weights)}] = {{\n"
                f"{self._array_initializer(layer.weights)}\n}};\n"
            )
            pieces.append(
                f"static const i32 B_{layer.identifier}[{len(layer.bias)}] = {{\n"
                f"{self._array_initializer(layer.bias)}\n}};\n"
            )
        for layer in self.linear_layers:
            pieces.append(
                f"static const i8 W_{layer.identifier}[{len(layer.weights)}] = {{\n"
                f"{self._array_initializer(layer.weights)}\n}};\n"
            )
            pieces.append(
                f"static const i32 B_{layer.identifier}[{len(layer.bias)}] = {{\n"
                f"{self._array_initializer(layer.bias)}\n}};\n"
            )
        return "\n".join(pieces)

    def _emit_layer_structs(self) -> str:
        pieces: list[str] = []
        for layer in self.conv_layers:
            activation_code = {"none": 0, "relu": 1, "relu6": 2}[layer.activation]
            pieces.append(
                dedent(
                    f"""
                    static const ConvLayer L_{layer.identifier} = {{
                      {layer.input_shape.channels}, {layer.input_shape.height}, {layer.input_shape.width},
                      {layer.output_shape.channels}, {layer.output_shape.height}, {layer.output_shape.width},
                      {layer.kernel_h}, {layer.kernel_w}, {layer.stride}, {layer.pad_h}, {layer.pad_w},
                      {layer.groups},
                      W_{layer.identifier}, B_{layer.identifier},
                      {layer.multiplier_numerator}LL, {layer.multiplier_denominator}LL,
                      {activation_code}, {layer.activation_upper}
                    }};
                    """
                ).strip()
            )
        for layer in self.linear_layers:
            pieces.append(
                dedent(
                    f"""
                    static const LinearLayer L_{layer.identifier} = {{
                      {layer.in_features}, {layer.out_features},
                      W_{layer.identifier}, B_{layer.identifier},
                      {layer.multiplier_numerator}LL, {layer.multiplier_denominator}LL
                    }};
                    """
                ).strip()
            )
        return "\n\n".join(pieces)

    def top_cpp(self) -> str:
        if not self.ops:
            self.emit_model_ops()
        arrays = self._emit_layer_arrays()
        structs = self._emit_layer_structs()
        ops = "\n".join(self.ops)
        return dedent(
            f"""
            #include <algorithm>
            #include <climits>
            #include <cstdint>
            #include <vector>

            using i8 = signed char;
            using i32 = int;
            using i64 = long long;

            struct ConvLayer {{
              int in_c;
              int in_h;
              int in_w;
              int out_c;
              int out_h;
              int out_w;
              int kernel_h;
              int kernel_w;
              int stride;
              int pad_h;
              int pad_w;
              int groups;
              const i8* weights;
              const i32* bias;
              i64 multiplier_numerator;
              i64 multiplier_denominator;
              int activation;  // 0 none, 1 ReLU, 2 ReLU6
              int activation_upper;
            }};

            struct LinearLayer {{
              int in_features;
              int out_features;
              const i8* weights;
              const i32* bias;
              i64 multiplier_numerator;
              i64 multiplier_denominator;
            }};

            static i64 clamp_i32(i64 value) {{
              if (value < static_cast<i64>(INT32_MIN)) return static_cast<i64>(INT32_MIN);
              if (value > static_cast<i64>(INT32_MAX)) return static_cast<i64>(INT32_MAX);
              return value;
            }}

            static i8 clamp_i8_symmetric(i64 value) {{
              if (value < -127) return static_cast<i8>(-127);
              if (value > 127) return static_cast<i8>(127);
              return static_cast<i8>(value);
            }}

            static i64 round_divide_nearest_even(i64 numerator, i64 denominator) {{
              if (denominator <= 0) return 0;
              const int sign = numerator < 0 ? -1 : 1;
              unsigned long long absolute = numerator < 0
                ? static_cast<unsigned long long>(-numerator)
                : static_cast<unsigned long long>(numerator);
              const unsigned long long divisor = static_cast<unsigned long long>(denominator);
              unsigned long long quotient = absolute / divisor;
              const unsigned long long remainder = absolute % divisor;
              const unsigned long long twice = remainder * 2ULL;
              const bool increment =
                (twice > divisor) || ((twice == divisor) && ((quotient & 1ULL) == 1ULL));
              if (increment) {{
                quotient += 1ULL;
              }}
              const i64 rounded = static_cast<i64>(quotient);
              return sign < 0 ? -rounded : rounded;
            }}

            static i8 requantize_i8(i64 accumulator, i64 numerator, i64 denominator) {{
              const i64 scaled = round_divide_nearest_even(accumulator * numerator, denominator);
              return clamp_i8_symmetric(scaled);
            }}

            static i8 apply_activation(i8 value, int activation, int activation_upper) {{
              int v = static_cast<int>(value);
              if (activation == 1) {{
                if (v < 0) v = 0;
              }} else if (activation == 2) {{
                if (v < 0) v = 0;
                if (v > activation_upper) v = activation_upper;
              }}
              return static_cast<i8>(v);
            }}

            static int index3(int c, int h, int w, int height, int width) {{
              return (c * height + h) * width + w;
            }}

            static void conv2d_layer(
                const std::vector<i8>& input,
                std::vector<i8>& output,
                const ConvLayer& layer) {{
              output.assign(layer.out_c * layer.out_h * layer.out_w, static_cast<i8>(0));
              const int output_per_group = layer.out_c / layer.groups;
              const int channels_per_group = layer.in_c / layer.groups;
              for (int oc = 0; oc < layer.out_c; ++oc) {{
                const int group = oc / output_per_group;
                const int in_start = group * channels_per_group;
                for (int oh = 0; oh < layer.out_h; ++oh) {{
                  for (int ow = 0; ow < layer.out_w; ++ow) {{
                    i64 acc = static_cast<i64>(layer.bias[oc]);
                    for (int ic_local = 0; ic_local < channels_per_group; ++ic_local) {{
                      const int ic = in_start + ic_local;
                      for (int kh = 0; kh < layer.kernel_h; ++kh) {{
                        const int ih = oh * layer.stride + kh - layer.pad_h;
                        if (ih < 0 || ih >= layer.in_h) continue;
                        for (int kw = 0; kw < layer.kernel_w; ++kw) {{
                          const int iw = ow * layer.stride + kw - layer.pad_w;
                          if (iw < 0 || iw >= layer.in_w) continue;
                          const int input_index = index3(ic, ih, iw, layer.in_h, layer.in_w);
                          const int weight_index =
                            ((oc * channels_per_group + ic_local) * layer.kernel_h + kh)
                              * layer.kernel_w + kw;
                          acc += static_cast<i64>(input[input_index])
                            * static_cast<i64>(layer.weights[weight_index]);
                        }}
                      }}
                    }}
                    acc = clamp_i32(acc);
                    i8 value = requantize_i8(
                      acc, layer.multiplier_numerator, layer.multiplier_denominator);
                    value = apply_activation(value, layer.activation, layer.activation_upper);
                    output[index3(oc, oh, ow, layer.out_h, layer.out_w)] = value;
                  }}
                }}
              }}
            }}

            static void rescale_tensor(
                const std::vector<i8>& input,
                std::vector<i8>& output,
                i64 numerator,
                i64 denominator) {{
              output.resize(input.size());
              for (size_t index = 0; index < input.size(); ++index) {{
                output[index] = requantize_i8(
                  static_cast<i64>(input[index]), numerator, denominator);
              }}
            }}

            static void residual_add_tensor(
                const std::vector<i8>& left,
                const std::vector<i8>& right,
                std::vector<i8>& output) {{
              output.resize(left.size());
              for (size_t index = 0; index < left.size(); ++index) {{
                const i64 value =
                  static_cast<i64>(left[index]) + static_cast<i64>(right[index]);
                output[index] = clamp_i8_symmetric(value);
              }}
            }}

            static void avg_pool_global(
                const std::vector<i8>& input,
                std::vector<i8>& output,
                int channels,
                int height,
                int width) {{
              output.assign(channels, static_cast<i8>(0));
              const i64 denominator = static_cast<i64>(height) * static_cast<i64>(width);
              for (int c = 0; c < channels; ++c) {{
                i64 sum = 0;
                for (int h = 0; h < height; ++h) {{
                  for (int w = 0; w < width; ++w) {{
                    sum += static_cast<i64>(input[index3(c, h, w, height, width)]);
                  }}
                }}
                output[c] = clamp_i8_symmetric(round_divide_nearest_even(sum, denominator));
              }}
            }}

            static void linear_layer(
                const std::vector<i8>& input,
                std::vector<i8>& output,
                const LinearLayer& layer) {{
              output.assign(layer.out_features, static_cast<i8>(0));
              for (int out = 0; out < layer.out_features; ++out) {{
                i64 acc = static_cast<i64>(layer.bias[out]);
                for (int in = 0; in < layer.in_features; ++in) {{
                  const int weight_index = out * layer.in_features + in;
                  acc += static_cast<i64>(input[in])
                    * static_cast<i64>(layer.weights[weight_index]);
                }}
                acc = clamp_i32(acc);
                output[out] = requantize_i8(
                  acc, layer.multiplier_numerator, layer.multiplier_denominator);
              }}
            }}

            {arrays}

            {structs}

            extern "C" void fourstage_top(const i8 input[{INPUT_SIZE}], i8 output[{OUTPUT_CLASSES}]) {{
              std::vector<i8> x(input, input + {INPUT_SIZE});
              std::vector<i8> y;
            {ops}
              for (int index = 0; index < {OUTPUT_CLASSES}; ++index) {{
                output[index] = x[index];
              }}
            }}
            """
        ).lstrip()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--int8-reference-summary", default=str(DEFAULT_INT8_SUMMARY))
    parser.add_argument("--output-root", default=str(DEFAULT_OUTPUT_ROOT))
    parser.add_argument("--summary", default=str(DEFAULT_SUMMARY))
    parser.add_argument("--vitis-hls", default=str(DEFAULT_VITIS_HLS))
    parser.add_argument(
        "--run-vitis",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Run Vitis HLS csim_design after generating the C++ harness.",
    )
    parser.add_argument(
        "--candidate-limit",
        type=int,
        default=None,
        help="Debug-only candidate limit; omitted for the formal gate.",
    )
    return parser.parse_args()


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def evidence(path: Path) -> dict[str, Any]:
    return {
        "path": str(path.resolve()),
        "sha256": sha256_file(path),
        "size_bytes": path.stat().st_size,
    }


def maybe_evidence(path: Path) -> dict[str, Any] | None:
    return evidence(path) if path.is_file() else None


def git_output(*args: str) -> str:
    completed = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip()


def safe_name(text: str) -> str:
    return "".join(ch if ch.isalnum() or ch in {"-", "_"} else "_" for ch in text)


def cpp_string(path: Path) -> str:
    return str(path.resolve()).replace("\\", "/")


def array_initializer(values: list[int], *, per_line: int = 24) -> str:
    chunks: list[str] = []
    for offset in range(0, len(values), per_line):
        chunks.append(
            "  " + ", ".join(str(int(value)) for value in values[offset : offset + per_line])
        )
    return ",\n".join(chunks)


def quantized_reference_inputs(
    reference_records: list[dict[str, Any]],
    *,
    input_scale: float,
) -> list[list[int]]:
    """Rebuild the exact input tensors from records if cached tensors exist.

    The C-sim harness only needs the INT8 tensors that the Python reference used.
    Earlier gates stored logits, not full input tensors, so this script rebuilds
    them from the original training-only dataset when the per-record tensor cache
    is unavailable.
    """

    tensors: list[list[int]] = []
    for row in reference_records:
        if "input_int8" not in row:
            raise ValueError(
                "python_int8_reference.json does not contain cached input_int8; "
                "rerun run_fourstage_int8_reference_gate.py after this gate adds "
                "input caching, or provide a reference payload with input_int8."
            )
        values = [int(value) for value in row["input_int8"]]
        if len(values) != INPUT_SIZE:
            raise ValueError(f"unexpected cached input length: {len(values)}")
        tensors.append(values)
    if not tensors:
        raise ValueError("reference payload has no records")
    return tensors


def rebuild_inputs_from_summary_if_needed(
    reference_payload: dict[str, Any],
    calibration: dict[str, Any],
    *,
    candidate_row: dict[str, Any],
    int8_summary: dict[str, Any],
) -> list[list[int]]:
    """Return quantized inputs, rebuilding and caching them when necessary."""

    records = reference_payload["reference_records"]
    if all("input_int8" in row for row in records):
        return quantized_reference_inputs(records, input_scale=float(calibration["scales"]["input"]))

    # Import lazily so normal test collection does not require dataset access.
    import yaml  # noqa: PLC0415
    from torch.utils.data import DataLoader, Subset  # noqa: PLC0415

    from hwnas_fpga.data.dataset import NKSIDDataset  # noqa: PLC0415
    from hwnas_fpga.data.protocol import build_protocol_split  # noqa: PLC0415

    protocol_path = Path(int8_summary["protocol_file"]["path"]).resolve()
    protocol = yaml.safe_load(protocol_path.read_text(encoding="utf-8"))
    dataset_cfg = protocol["dataset"]
    data_dir = Path(int8_summary["calibration_dataset"]["data_dir"]).resolve()
    dataset = NKSIDDataset(
        data_dir=str(data_dir),
        image_size=int(dataset_cfg["image_size"]),
        is_training=False,
        fold=0,
        use_kfold=False,
        split="full",
        output_channels=int(dataset_cfg["input_channels"]),
        image_error_policy="raise",
        geometry_mode=str(dataset_cfg["geometry_mode"]),
        fixed_scale_factor=dataset_cfg.get("fixed_scale_factor"),
        geometry_padding_value=int(dataset_cfg["geometry_padding_value"]),
        augmentation_profile=str(dataset_cfg["augmentation_profile"]),
        cache_decoded_images=False,
        cache_geometry_images=False,
    )
    split = build_protocol_split(
        dataset.samples,
        str(data_dir),
        fold_index=0,
        seed=42,
        inner_val_fraction=float(dataset_cfg["inner_val_fraction"]),
        num_classes=OUTPUT_CLASSES,
    )
    train_indices = list(split.train_indices)
    expected_indices = [int(row["dataset_index"]) for row in records]
    if expected_indices != train_indices[: len(expected_indices)]:
        raise ValueError(
            f"{candidate_row['arch_id']}: reference indices do not match "
            "Protocol V2 fold0/seed42 training prefix"
        )
    loader = DataLoader(Subset(dataset, expected_indices), batch_size=1, shuffle=False, num_workers=0)
    tensors: list[list[int]] = []
    for inputs, _labels in loader:
        quantized = quantize_symmetric_int8(
            inputs.cpu(), scale=float(calibration["scales"]["input"])
        )
        values = [int(value) for value in quantized.reshape(-1).tolist()]
        if len(values) != INPUT_SIZE:
            raise ValueError(f"unexpected rebuilt input length: {len(values)}")
        tensors.append(values)
    if len(tensors) != len(records):
        raise ValueError("rebuilt input count does not match reference records")
    return tensors


def testbench_cpp(
    *,
    input_samples: list[list[int]],
    expected_outputs: list[list[int]],
    result_path: Path,
) -> str:
    samples = ",\n".join(
        "{\n" + array_initializer(sample) + "\n}" for sample in input_samples
    )
    expected = ",\n".join(
        "{ " + ", ".join(str(int(value)) for value in row) + " }"
        for row in expected_outputs
    )
    sample_count = len(input_samples)
    return dedent(
        f"""
        #include <fstream>
        #include <iostream>

        using i8 = signed char;

        extern "C" void fourstage_top(const i8 input[{INPUT_SIZE}], i8 output[{OUTPUT_CLASSES}]);

        static const i8 SAMPLE_INPUTS[{sample_count}][{INPUT_SIZE}] = {{
        {samples}
        }};

        static const i8 EXPECTED[{sample_count}][{OUTPUT_CLASSES}] = {{
        {expected}
        }};

        int main() {{
          const char* result_path = "{cpp_string(result_path)}";
          int mismatch_count = 0;
          int checked_outputs = 0;
          int max_abs_mismatch = 0;
          for (int sample = 0; sample < {sample_count}; ++sample) {{
            i8 output[{OUTPUT_CLASSES}] = {{0}};
            fourstage_top(SAMPLE_INPUTS[sample], output);
            for (int index = 0; index < {OUTPUT_CLASSES}; ++index) {{
              ++checked_outputs;
              const int diff = static_cast<int>(output[index]) - static_cast<int>(EXPECTED[sample][index]);
              const int abs_diff = diff < 0 ? -diff : diff;
              if (diff != 0) {{
                ++mismatch_count;
                if (abs_diff > max_abs_mismatch) {{
                  max_abs_mismatch = abs_diff;
                }}
                std::cout << "MISMATCH sample=" << sample
                          << " output=" << index
                          << " got=" << static_cast<int>(output[index])
                          << " expected=" << static_cast<int>(EXPECTED[sample][index])
                          << "\\n";
              }}
            }}
          }}
          std::ofstream json(result_path);
          json << "{{\\n";
          json << "  \\"schema_version\\": 1,\\n";
          json << "  \\"status\\": \\"" << (mismatch_count == 0 ? "PASS" : "FAIL") << "\\",\\n";
          json << "  \\"sample_count\\": {sample_count},\\n";
          json << "  \\"output_count\\": " << checked_outputs << ",\\n";
          json << "  \\"mismatch_count\\": " << mismatch_count << ",\\n";
          json << "  \\"max_abs_mismatch\\": " << max_abs_mismatch << "\\n";
          json << "}}\\n";
          json.close();
          std::cout << "CSIM_STATUS " << (mismatch_count == 0 ? "PASS" : "FAIL")
                    << " mismatch_count=" << mismatch_count
                    << " checked_outputs=" << checked_outputs << "\\n";
          return mismatch_count == 0 ? 0 : 1;
        }}
        """
    ).lstrip()


def tcl_script() -> str:
    return dedent(
        """
        open_project -reset project
        set_top fourstage_top
        add_files fourstage_top.cpp -cflags {-std=c++17 -O2}
        add_files -tb fourstage_tb.cpp -cflags {-std=c++17 -O2}
        open_solution -reset solution1 -flow_target vivado
        set_part {xc7k325tffg900-2}
        create_clock -period 5.000 -name default
        csim_design
        exit
        """
    ).lstrip()


def write_harness(
    *,
    model: torch.nn.Module,
    calibration: dict[str, Any],
    reference_payload: dict[str, Any],
    candidate: dict[str, Any],
    csim_dir: Path,
    int8_summary: dict[str, Any],
) -> dict[str, Any]:
    emitter = CppNetworkEmitter(model, calibration)
    top = emitter.top_cpp()
    input_samples = rebuild_inputs_from_summary_if_needed(
        reference_payload,
        calibration,
        candidate_row=candidate,
        int8_summary=int8_summary,
    )
    expected_outputs = [
        [int(value) for value in row["logits_int8"]]
        for row in reference_payload["reference_records"]
    ]
    if any(len(row) != OUTPUT_CLASSES for row in expected_outputs):
        raise ValueError(f"{candidate['arch_id']}: expected output length is not {OUTPUT_CLASSES}")
    csim_dir.mkdir(parents=True, exist_ok=True)
    top_path = csim_dir / "fourstage_top.cpp"
    tb_path = csim_dir / "fourstage_tb.cpp"
    tcl_path = csim_dir / "run_csim.tcl"
    result_path = csim_dir / "csim_result.json"
    top_path.write_text(top, encoding="utf-8")
    tb_path.write_text(
        testbench_cpp(
            input_samples=input_samples,
            expected_outputs=expected_outputs,
            result_path=result_path,
        ),
        encoding="utf-8",
    )
    tcl_path.write_text(tcl_script(), encoding="utf-8")
    harness_payload = {
        "schema_version": 1,
        "contract": CALIBRATION_CONTRACT,
        "candidate": {
            "role": candidate["role"],
            "arch_id": candidate["arch_id"],
        },
        "input_size": INPUT_SIZE,
        "output_classes": OUTPUT_CLASSES,
        "sample_count": len(input_samples),
        "conv_layer_count": len(emitter.conv_layers),
        "linear_layer_count": len(emitter.linear_layers),
        "generated_files": {
            "top": evidence(top_path),
            "testbench": evidence(tb_path),
            "tcl": evidence(tcl_path),
        },
        "claim_boundary": (
            "Generated C++ integer C-sim parity harness. This is not a "
            "synthesizable full-network HLS datapath claim."
        ),
    }
    manifest_path = csim_dir / "csim_harness_manifest.json"
    harness_payload["payload_sha256"] = canonical_sha256(harness_payload)
    write_json(manifest_path, harness_payload)
    return {
        "manifest": evidence(manifest_path),
        "top": evidence(top_path),
        "testbench": evidence(tb_path),
        "tcl": evidence(tcl_path),
        "result_path": str(result_path.resolve()),
    }


def run_vitis_csim(*, vitis_hls: Path, csim_dir: Path) -> tuple[int, Path]:
    log_path = csim_dir / "vitis_hls_csim.log"
    completed = subprocess.run(
        [str(vitis_hls), "-f", "run_csim.tcl"],
        cwd=csim_dir,
        check=False,
        capture_output=True,
        text=True,
        timeout=None,
    )
    log_path.write_text(
        "STDOUT\n"
        + completed.stdout
        + "\nSTDERR\n"
        + completed.stderr
        + "\n",
        encoding="utf-8",
        errors="replace",
    )
    return completed.returncode, log_path


def run_one_candidate(
    candidate: dict[str, Any],
    *,
    output_root: Path,
    vitis_hls: Path,
    run_vitis: bool,
    int8_summary: dict[str, Any],
) -> dict[str, Any]:
    checkpoint = Path(candidate["source_checkpoint"]["path"]).resolve()
    if sha256_file(checkpoint) != candidate["source_checkpoint"]["sha256"]:
        raise RuntimeError(f"{candidate['arch_id']}: checkpoint SHA mismatch")
    calibration_path = Path(candidate["activation_calibration"]["path"]).resolve()
    reference_path = Path(candidate["python_int8_reference"]["path"]).resolve()
    if sha256_file(calibration_path) != candidate["activation_calibration"]["sha256"]:
        raise RuntimeError(f"{candidate['arch_id']}: activation calibration SHA mismatch")
    if sha256_file(reference_path) != candidate["python_int8_reference"]["sha256"]:
        raise RuntimeError(f"{candidate['arch_id']}: Python INT8 reference SHA mismatch")

    calibration = read_json(calibration_path)
    reference_payload = read_json(reference_path)
    model, _architecture, _payload, _class_names = load_checkpoint_model(checkpoint, device="cpu")

    csim_dir = (
        output_root
        / f"{safe_name(candidate['role'])}__{safe_name(candidate['arch_id'])}"
        / "fold0_seed42"
        / "csim"
    )
    harness = write_harness(
        model=model,
        calibration=calibration,
        reference_payload=reference_payload,
        candidate=candidate,
        csim_dir=csim_dir,
        int8_summary=int8_summary,
    )

    result_path = Path(harness["result_path"])
    if result_path.exists():
        # Replace only this gate-owned result file so stale mismatches cannot
        # accidentally satisfy the current run.
        result_path.unlink()

    if not run_vitis:
        return {
            "role": candidate["role"],
            "arch_id": candidate["arch_id"],
            "status": "NOT_RUN",
            "sample_count": len(reference_payload["reference_records"]),
            "output_count": len(reference_payload["reference_records"]) * OUTPUT_CLASSES,
            "mismatch_count": None,
            "csim_project_dir": str(csim_dir.resolve()),
            "harness": harness,
            "vitis_returncode": None,
            "vitis_log": None,
            "csim_result": None,
            "claim_boundary": "Harness generated only; Vitis C-sim was not run.",
        }

    returncode, log_path = run_vitis_csim(vitis_hls=vitis_hls, csim_dir=csim_dir)
    result_payload = read_json(result_path) if result_path.is_file() else None
    mismatch_count = (
        int(result_payload["mismatch_count"])
        if isinstance(result_payload, dict) and "mismatch_count" in result_payload
        else None
    )
    status = (
        "PASS"
        if returncode == 0
        and isinstance(result_payload, dict)
        and result_payload.get("status") == "PASS"
        and mismatch_count == 0
        else "FAIL"
    )
    return {
        "role": candidate["role"],
        "arch_id": candidate["arch_id"],
        "status": status,
        "sample_count": (
            int(result_payload["sample_count"])
            if isinstance(result_payload, dict) and "sample_count" in result_payload
            else len(reference_payload["reference_records"])
        ),
        "output_count": (
            int(result_payload["output_count"])
            if isinstance(result_payload, dict) and "output_count" in result_payload
            else len(reference_payload["reference_records"]) * OUTPUT_CLASSES
        ),
        "mismatch_count": mismatch_count,
        "max_abs_mismatch": (
            int(result_payload["max_abs_mismatch"])
            if isinstance(result_payload, dict) and "max_abs_mismatch" in result_payload
            else None
        ),
        "csim_project_dir": str(csim_dir.resolve()),
        "harness": harness,
        "vitis_returncode": int(returncode),
        "vitis_log": evidence(log_path),
        "csim_result": maybe_evidence(result_path),
        "claim_boundary": (
            "Vitis HLS C-sim parity against the Python INT8 reference only; "
            "not RTL co-sim, HLS synthesis, route, bitstream, COM5, or power."
        ),
    }


def main() -> int:
    args = parse_args()
    int8_summary_path = Path(args.int8_reference_summary).expanduser().resolve()
    output_root = Path(args.output_root).expanduser().resolve()
    summary_path = Path(args.summary).expanduser().resolve()
    vitis_hls = Path(args.vitis_hls).expanduser().resolve()
    int8_summary = read_json(int8_summary_path)
    if int8_summary.get("status") != "PASS":
        raise RuntimeError("Python INT8 reference gate must PASS before C-sim")
    if int8_summary.get("contract") != CALIBRATION_CONTRACT:
        raise RuntimeError("unexpected INT8 calibration contract")
    candidates = list(int8_summary["candidates"])
    formal_candidate_count = len(candidates)
    if args.candidate_limit is not None:
        candidates = candidates[: int(args.candidate_limit)]
    if args.run_vitis and not vitis_hls.is_file():
        payload = {
            "schema_version": 1,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "status": "BLOCKED",
            "gate": "full_network_csim_zero_mismatch",
            "blocker": f"Vitis HLS executable not found: {vitis_hls}",
            "int8_reference_summary": evidence(int8_summary_path),
            "candidate_count": len(candidates),
            "candidates": [],
            "downstream_gates": {
                "rtl_cosim": "PENDING",
                "full_network_hls": "PENDING",
                "place_and_route_5ns": "PENDING",
                "bitstream": "NOT_GENERATED",
                "com5_board_latency": "NOT_RUN",
                "external_meter_power": "NOT_MEASURED",
            },
        }
        payload["payload_sha256"] = canonical_sha256(payload)
        write_json(summary_path, payload)
        print(json.dumps(payload, indent=2, ensure_ascii=False))
        return 2

    rows = [
        run_one_candidate(
            candidate,
            output_root=output_root,
            vitis_hls=vitis_hls,
            run_vitis=bool(args.run_vitis),
            int8_summary=int8_summary,
        )
        for candidate in candidates
    ]
    formal_scope = args.candidate_limit is None and len(rows) == formal_candidate_count
    rows_pass = rows and all(
        row["status"] == "PASS" and row["mismatch_count"] == 0 for row in rows
    )
    if not bool(args.run_vitis):
        status = "NOT_RUN"
    elif formal_scope and rows_pass:
        status = "PASS"
    elif rows_pass:
        status = "PARTIAL_PASS_NOT_FORMAL"
    else:
        status = "FAIL"
    payload = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": status,
        "gate": "full_network_csim_zero_mismatch",
        "contract": CALIBRATION_CONTRACT,
        "int8_reference_summary": evidence(int8_summary_path),
        "vitis_hls": {
            "path": str(vitis_hls),
            "exists": vitis_hls.is_file(),
        },
        "git": {
            "head": git_output("rev-parse", "HEAD"),
            "branch": git_output("branch", "--show-current"),
            "status_porcelain": git_output("status", "--porcelain=v1").splitlines(),
        },
        "candidate_count": len(rows),
        "formal_candidate_count": formal_candidate_count,
        "formal_scope": formal_scope,
        "candidate_limit": args.candidate_limit,
        "candidates": rows,
        "zero_mismatch": status in {"PASS", "PARTIAL_PASS_NOT_FORMAL"},
        "downstream_gates": {
            "rtl_cosim": "PENDING",
            "full_network_hls": "PENDING",
            "place_and_route_5ns": "PENDING",
            "bitstream": "NOT_GENERATED",
            "com5_board_latency": "NOT_RUN",
            "external_meter_power": "NOT_MEASURED",
        },
        "claim_boundary": (
            "Complete-network C-sim integer parity is separate from "
            "synthesizable HLS, RTL co-sim, full-network place-and-route, "
            "bitstream, COM5 board execution, and external-meter power."
        ),
    }
    payload["payload_sha256"] = canonical_sha256(payload)
    write_json(summary_path, payload)
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    return 0 if status in {"PASS", "PARTIAL_PASS_NOT_FORMAL"} else 1


if __name__ == "__main__":
    raise SystemExit(main())
